# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nothing to see here
#email: cameron.hart@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Maybe this will be a blog about programming in C/C++ and Rust.
  Or maybe it will be a desolate wasteland of infrequent posts and spam bot
  comments.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bitshifter.github.io" # the base hostname & protocol for your site
twitter_username: bitshifternz
github_username:  bitshifter
exclude: ["Session.vim", "*.swp"]
keep_files: [".git"]

# Build settings
markdown: kramdown

kramdown:
  input: GFM
